# Generated by Django 2.0.5 on 2018-06-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomName', models.CharField(max_length=128, verbose_name='Bom����')),
                ('bomVersion', models.CharField(max_length=20, verbose_name='Bom�汾')),
                ('bomContext', models.TextField(max_length=128, verbose_name='Bom����')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperName', models.CharField(max_length=128, verbose_name='ͼֽ����')),
                ('paperVersion', models.CharField(max_length=20, verbose_name='ͼֽ�汾')),
                ('paperDiscrib', models.CharField(max_length=128, verbose_name='ͼֽ����')),
                ('paperAddr', models.TextField(max_length=256, verbose_name='ͼֽ��ַ')),
            ],
        ),
        migrations.CreateModel(
            name='Product2Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=128, verbose_name='��Ʒ����')),
                ('bomName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='View.Bom')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('paperName', 'paperVersion')},
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('bomName', 'bomVersion')},
        ),
    ]
