# Generated by Django 2.0.5 on 2018-06-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0002_auto_20180604_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='bomContext',
            field=models.TextField(verbose_name='Bom内容'),
        ),
    ]
