# Generated by Django 2.0.5 on 2018-06-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0003_auto_20180604_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product2bom',
            name='id',
        ),
        migrations.AlterField(
            model_name='product2bom',
            name='productName',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='产品名'),
        ),
    ]
