# Generated by Django 2.0.5 on 2018-06-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0004_auto_20180604_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name': 'BOM单'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': '图纸'},
        ),
        migrations.AlterModelOptions(
            name='product2bom',
            options={'verbose_name': '产品BOM单'},
        ),
        migrations.AlterField(
            model_name='product2bom',
            name='bomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='View.Bom', verbose_name='Bom名'),
        ),
    ]
