# Generated by Django 2.0.5 on 2018-06-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0005_auto_20180611_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_user', models.CharField(max_length=128, verbose_name='用户名')),
                ('log_time', models.DateTimeField(auto_now=True, verbose_name='访问时间')),
                ('log_table', models.CharField(default='', max_length=128, verbose_name='访问表名')),
                ('log_action', models.TextField(max_length=256, verbose_name='操作')),
            ],
            options={
                'verbose_name': '图纸',
            },
        ),
    ]
