# Generated by Django 2.0.6 on 2018-06-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '状态',
            },
        ),
    ]
