# Generated by Django 2.0.6 on 2018-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0002_auto_20180626_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='owner',
            field=models.CharField(default='', max_length=128, verbose_name='所有者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='owner',
            field=models.CharField(default='', max_length=128, verbose_name='所有者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(default='', max_length=128, verbose_name='所有者'),
            preserve_default=False,
        ),
    ]
