# Generated by Django 2.0.6 on 2018-06-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0003_auto_20180626_1258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('productName', 'bom')},
        ),
    ]
